insert into storage.buckets (id, name, public)
values ('quote-uploads', 'quote-uploads', false)
on conflict (id) do nothing;

create table if not exists public.quote_requests (
  id bigint generated by default as identity primary key,
  request_id text not null unique,
  received_at timestamptz not null,
  customer_name text,
  customer_email text,
  customer_phone text,
  shipping_address text,
  shipping_city text,
  shipping_pincode text,
  customer_notes text,
  original_filename text,
  saved_filename text,
  upload_path text,
  material text,
  price text,
  weight text,
  volume text,
  print_time text,
  lead_time text,
  created_at timestamptz not null default now()
);
